name: project_template
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: any
  logger: ^2.0.2+1
  octo_image: ^2.0.0
  provider: ^6.1.1
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: any
  flutter_gen_runner: any
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/files/
    - assets/fonts/

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true
    lottie: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
